#!/data/data/com.termux/files/usr/bin/bash
# Tailscale setup for Razr Ultra 25 <-> Jetson Orin Nano Super
# Termux uses the Tailscale Android app for the VPN tunnel

echo "=== Tailscale Setup for N0.V4 ==="
echo ""
echo "Tailscale on Android works via the app, not Termux directly."
echo "The app creates a VPN that Termux can use automatically."
echo ""
echo "--- Step 1: Install Tailscale on Razr ---"
echo ""
echo "Install from Play Store: search 'Tailscale'"
echo "Or download APK from: tailscale.com/downloads/android"
echo ""
echo "--- Step 2: Connect Razr to your tailnet ---"
echo ""
echo "1. Open Tailscale app"
echo "2. Sign in with your account"
echo "3. Toggle ON"
echo "4. Approve the VPN connection in Android prompt"
echo ""
echo "--- Step 3: Install Tailscale on Jetson ---"
echo ""
echo "SSH to your Jetson, then run:"
echo ""
echo "  curl -fsSL https://tailscale.com/install.sh | sh"
echo ""
echo "  sudo tailscale up"
echo ""
echo "Sign in on the Jetson too (browser or auth URL)."
echo ""
echo "--- Step 4: Find Jetson's Tailscale IP ---"
echo ""
echo "On Jetson:"
echo ""
echo "  tailscale ip -4"
echo ""
echo "--- Step 5: Update N0.V4 config with Jetson IP ---"
echo ""
echo "In Termux:"
echo ""
echo "  nano ~/android-cowork/nova/routing_rules.json"
echo ""
echo "Replace 'jetson.local' with your Jetson's Tailscale IP."
echo ""
echo "--- Step 6: Test connection from Termux ---"
echo ""
echo "  ping JETSON-TAILSCALE-IP"
echo ""
echo "  curl http://JETSON-TAILSCALE-IP:11434/api/version"
echo ""
echo "--- Useful commands (on Jetson) ---"
echo ""
echo "  tailscale status           # see all devices"
echo "  tailscale ping DEVICE-IP   # test connectivity"
echo "  sudo tailscale set --ssh   # enable Tailscale SSH (then: ssh -t ts jetson)"
echo ""

# Save Jetson IP to env file if provided
if [ -n "$JETSON_IP" ]; then
  echo "export JETSON_IP=\"$JETSON_IP\"" >> ~/android-cowork/config/vertex_env.sh
  echo "JETSON_IP=$JETSON_IP saved to vertex_env.sh"
fi
